trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '../../Avelraangame.Avelraangame.sln'
  project: '../../Avelraangame.Avelraangame.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'NuGet tool installer'
    inputs:
      command: 'restore'

  - task: DotNetCoreCLI@2
    displayName: 'Restore and publish NuGet packages'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(BuildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Publish artifacts'
    inputs:
      command: 'publish'
      publishWebProjects: true
      arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts to Azure App Service'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: AzureTestProject
